version: '3'

# docker compose --env-file .env.{dev,test}.local up {test_db,dev_db} -d
# docker compose rm {test_db,dev_db} -s -f -v # jika volume nya diberi nama maka volume tersebut tidak ikut terhapus
# docker compose --env-file .env.{dev,test}.local down -v # menghapus container dan semua volume

services:
  dev_db:
    image: lite-note-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: lite-note-db-dev
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOSTNAME=localhost
    ports:
      - ${DB_PORT}:${DB_PORT}/tcp
    expose:
      - ${DB_PORT}
    healthcheck:
      test:  mongosh --port ${DB_PORT} --eval "db.stats().ok" --quiet
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s

  test_db:
    image: lite-note-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: lite-note-db-test
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOSTNAME=localhost
    ports:
      - ${DB_PORT}:${DB_PORT}/tcp
    expose:
      - ${DB_PORT}
    healthcheck:
      test:  mongosh --port ${DB_PORT} --eval "db.stats().ok" --quiet
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s
    