on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ci:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: >
          pnpm config set auto-install-peers true
          && pnpm install --frozen-lockfile
          && pnpm prisma generate
        
    # - name: Integration test

      - name: Start test container
        run: > 
          pnpm db:up:test
          && sleep 15

      - name:  End to end test
        run: >
          pnpm prisma:push:test 
          && pnpm test:e2e
