on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    name: API end to end test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      
      - name: Install dependencies
        run: >
          pnpm config set auto-install-peers true &&
          pnpm install --frozen-lockfile
    
      - name:  End to end test
        run: pnpm test:e2e
        
      
    
